(() => {
  'use strict';

  const STORAGE_KEY = 'autopulse-state-v1';
  const DB_NAME = 'autopulse-local';
  const DB_VERSION = 1;
  const icons = { oil: '◉', coolant: '❄', brake: '◌', gearbox: '⚙', air: '≋', cabin: '⌁', spark: '✦', timing: '↻', pads: '▣', battery: '▰', custom: '✚' };
  // Усреднённые стартовые ориентиры из пользовательских диапазонов.
  // Это не заводской регламент: точную цифру всегда можно поменять под модель.
  // Официальные руководства задают интервалы по конкретному двигателю, коробке,
  // маслу и тяжёлым условиям эксплуатации — поэтому каждый интервал редактируемый.
  const baseItems = [
    { id: 'oil', name: 'Масло двигателя', short: 'Двигатель', km: 11500, months: 9, domesticKm: 10000, domesticMonths: 8, kind: 'replace', description: 'Среднее: 8–15 тыс. км / 6–12 мес. · раньше при тяжёлых условиях' },
    { id: 'coolant', name: 'Антифриз / тосол', short: 'Охлаждение', km: 50000, months: 48, domesticKm: 45000, domesticMonths: 42, kind: 'replace', description: 'Среднее: 40–60 тыс. км / 3–5 лет' },
    { id: 'brake', name: 'Тормозная жидкость', short: 'Тормозная система', km: 25000, months: 24, domesticKm: 22000, domesticMonths: 24, kind: 'replace', description: 'Среднее: 20–30 тыс. км / 2 года · время важнее пробега' },
    { id: 'gearbox', name: 'Масло в коробке', short: 'Трансмиссия', km: 55000, months: 54, domesticKm: 50000, domesticMonths: 48, kind: 'replace', description: 'Среднее: 50–60 тыс. км / 3–6 лет · сверяйте тип коробки' },
    { id: 'air', name: 'Воздушный фильтр', short: 'Фильтры', km: 12500, months: 12, domesticKm: 10000, domesticMonths: 12, kind: 'replace', description: 'Среднее: 10–15 тыс. км / 1 год · в пыли осматривать чаще' },
    { id: 'cabin', name: 'Салонный фильтр', short: 'Фильтры', km: 12500, months: 12, domesticKm: 10000, domesticMonths: 12, kind: 'replace', description: 'Среднее: 10–15 тыс. км / 1 год' },
    { id: 'spark', name: 'Свечи зажигания', short: 'Зажигание', km: 45000, months: null, domesticKm: 35000, domesticMonths: null, kind: 'replace', description: 'Среднее: 30–60 тыс. км · зависит от типа свечей' },
    { id: 'timing', name: 'Ремень / цепь ГРМ', short: 'Двигатель', km: 90000, months: 72, domesticKm: 70000, domesticMonths: 66, kind: 'replace', description: 'Среднее: 60–120 тыс. км / 5–7 лет · критично для мотора' },
    { id: 'pads', name: 'Колодки и диски', short: 'Тормозная система', km: null, months: null, kind: 'check', description: 'Оценивается только по фактическому износу' },
    { id: 'battery', name: 'Аккумулятор', short: 'Электрика', km: null, months: 54, domesticKm: null, domesticMonths: 48, kind: 'replace', description: 'Среднее: 4–5 лет, но важнее тест ёмкости' }
  ];

  const defaultState = () => ({
    onboarded: false, page: 'home',
    vehicle: { type: 'foreign', make: '', model: '', year: new Date().getFullYear() - 5, mileage: 0, mileageUpdatedAt: null, reminderFrequency: 14, severeUse: false },
    items: baseItems.map(item => ({ ...item, customKm: null, customMonths: null, lastMileage: null, lastDate: null, records: [], photos: [] }))
  });

  let state = defaultState();
  let activeModal = null;
  let activeItemId = null;
  let customDraft = null;
  let onboardingStep = 1;
  let onboardingDraft = null;
  let toastTimer;
  const app = document.querySelector('#app');

  function openDb() { return new Promise((resolve, reject) => { const req = indexedDB.open(DB_NAME, DB_VERSION); req.onupgradeneeded = () => { if (!req.result.objectStoreNames.contains('state')) req.result.createObjectStore('state'); }; req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error); }); }
  async function loadState() { try { const db = await openDb(); const saved = await new Promise((resolve, reject) => { const req = db.transaction('state').objectStore('state').get('current'); req.onsuccess = () => resolve(req.result); req.onerror = () => reject(req.error); }); if (saved) return mergeState(saved); const legacy = localStorage.getItem(STORAGE_KEY); if (legacy) { const migrated = mergeState(JSON.parse(legacy)); await persistState(migrated); localStorage.removeItem(STORAGE_KEY); return migrated; } } catch (_) {} return defaultState(); }
  function mergeState(saved) {
    const fresh = defaultState();
    const savedItems = Array.isArray(saved.items) ? saved.items : [];
    const builtIn = fresh.items.map(base => ({ ...base, ...(savedItems.find(item => item.id === base.id) || {}) }));
    const custom = savedItems.filter(item => item.custom === true && !builtIn.some(base => base.id === item.id));
    return { ...fresh, ...saved, vehicle: { ...fresh.vehicle, ...(saved.vehicle || {}) }, items: [...builtIn, ...custom] };
  }
  async function persistState(value) { const db = await openDb(); return new Promise((resolve, reject) => { const req = db.transaction('state', 'readwrite').objectStore('state').put(value, 'current'); req.onsuccess = resolve; req.onerror = () => reject(req.error); }); }
  function save() { persistState(state).catch(() => showToast('Не удалось сохранить данные на устройстве')); }
  async function exportBackup() { const blob = new Blob([JSON.stringify({ app: 'AutoPulse', version: 1, exportedAt: new Date().toISOString(), state }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `autopulse-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); showToast('Резервная копия выгружена'); }
  function importBackup(file) { if (!file) return; const reader = new FileReader(); reader.onload = async () => { try { const parsed = JSON.parse(reader.result); const incoming = parsed.state || parsed; if (!incoming.vehicle || !incoming.items) throw new Error('bad backup'); state = mergeState(incoming); await persistState(state); activeModal = null; render(); showToast('Резервная копия восстановлена'); } catch (_) { showToast('Не удалось прочитать этот файл'); } }; reader.readAsText(file); }
  function esc(value) { return String(value ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
  function fmtKm(value) { return Number(value || 0).toLocaleString('ru-RU'); }
  function fmtDate(date) { return new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(date)); }
  function monthsSince(date) { return date ? Math.max(0, (Date.now() - new Date(date).getTime()) / (1000 * 60 * 60 * 24 * 30.44)) : null; }
  function monthsWord(n) { n = Math.abs(Math.round(n)); const mod10 = n % 10, mod100 = n % 100; if (mod10 === 1 && mod100 !== 11) return 'месяц'; if (mod10 >= 2 && mod10 <= 4 && (mod100 < 10 || mod100 >= 20)) return 'месяца'; return 'месяцев'; }
  function weeksWord(n) { n = Math.abs(Number(n)); if (n === 1) return 'неделю'; if (n >= 2 && n <= 4) return 'недели'; return 'недель'; }
  function currentItem(item) {
    const domestic = state.vehicle.type === 'domestic';
    let targetKm = item.customKm ?? (domestic ? item.domesticKm : item.km);
    let targetMonths = item.customMonths ?? (domestic ? item.domesticMonths : item.months);
    // Короткие поездки, пробки, пыль, морозы и буксировка считаются тяжёлыми условиями.
    if (state.vehicle.severeUse && targetKm) targetKm = Math.round(targetKm * .75);
    return { ...item, targetKm, targetMonths };
  }
  function getStatus(item) {
    item = currentItem(item);
    if (item.kind === 'check') return { key: 'neutral', label: 'Проверить', percent: 0, note: item.lastDate ? `Последняя проверка · ${fmtDate(item.lastDate)}` : 'Добавьте осмотр при следующем ТО' };
    if (!item.lastDate && item.lastMileage == null) return { key: 'neutral', label: 'Нет данных', percent: 0, note: 'Укажите, когда это обслуживали' };
    const kmUsed = item.lastMileage == null ? 0 : Math.max(0, state.vehicle.mileage - item.lastMileage);
    const kmRatio = item.targetKm ? kmUsed / item.targetKm : 0;
    const timeUsed = item.lastDate ? monthsSince(item.lastDate) : 0;
    const timeRatio = item.targetMonths ? timeUsed / item.targetMonths : 0;
    const ratio = Math.max(kmRatio, timeRatio);
    if (ratio >= 1) return { key: 'danger', label: 'Просрочено', percent: Math.min(100, Math.round(ratio * 100)), note: kmRatio >= timeRatio ? `Лимит через пробег · ${fmtKm(kmUsed)} из ${fmtKm(item.targetKm)} км` : `По времени · ${Math.floor(timeUsed)} из ${item.targetMonths} мес.` };
    if (ratio >= .78) return { key: 'warn', label: 'Скоро пора', percent: Math.round(ratio * 100), note: nextDue(item, kmUsed, timeUsed, kmRatio, timeRatio) };
    return { key: 'good', label: 'Всё ок', percent: Math.max(4, Math.round(ratio * 100)), note: nextDue(item, kmUsed, timeUsed, kmRatio, timeRatio) };
  }
  function nextDue(item, kmUsed, timeUsed, kmRatio, timeRatio) {
    const kmLeft = item.targetKm ? Math.max(0, item.targetKm - kmUsed) : Infinity;
    const monthsLeft = item.targetMonths ? Math.max(0, item.targetMonths - timeUsed) : Infinity;
    if (monthsLeft < Infinity && (kmLeft === Infinity || timeRatio >= kmRatio)) return `Примерно через ${Math.max(1, Math.round(monthsLeft))} ${monthsWord(monthsLeft)}`;
    if (kmLeft < Infinity) return `Осталось около ${fmtKm(kmLeft)} км`;
    return 'По состоянию детали';
  }
  function overallStatus() {
    const statuses = state.items.map(getStatus); if (statuses.some(s => s.key === 'danger')) return { key: 'danger', label: 'Есть просроченное' }; if (statuses.some(s => s.key === 'warn')) return { key: 'warn', label: 'Скоро потребуется ТО' }; if (statuses.some(s => s.key === 'neutral')) return { key: 'neutral', label: 'Нужно заполнить данные' }; return { key: 'good', label: 'Всё под контролем' };
  }
  function ageStatus() { const age = new Date().getFullYear() - Number(state.vehicle.year || new Date().getFullYear()); return age >= 20 ? 'critical' : age >= 15 ? 'old' : null; }
  function mileageReminderDue() { return state.vehicle.mileageUpdatedAt && (Date.now() - new Date(state.vehicle.mileageUpdatedAt).getTime()) >= state.vehicle.reminderFrequency * 24 * 60 * 60 * 1000; }
  function vehicleName() { return [state.vehicle.make, state.vehicle.model].filter(Boolean).join(' ') || 'Моя машина'; }

  function render() { if (!state.onboarded) renderOnboarding(); else renderApp(); }
  function renderApp() { app.innerHTML = `${state.page === 'home' ? homePage() : state.page === 'schedule' ? schedulePage() : historyPage()}${bottomNav()}${activeModal ? modalMarkup() : ''}<div class="toast" id="toast"></div>`; bindAppEvents(); }
  function homePage() {
    const overall = overallStatus(), age = ageStatus(), urgent = state.items.filter(i => ['danger', 'warn'].includes(getStatus(i).key)).sort((a,b) => getStatus(b).percent - getStatus(a).percent).slice(0, 4);
    return `<main class="screen page-enter"><header class="topbar"><div><div class="eyebrow">AutoPulse / журнал гаража</div><h1>Добрый день.</h1></div><button class="icon-btn" data-action="edit-vehicle" aria-label="Настройки машины">⚙</button></header>
      <section class="vehicle-hero"><div class="hud-corner">АП // 01</div><div class="hero-main"><div class="car-tag">${state.vehicle.type === 'domestic' ? 'отечественный профиль' : 'иностранный профиль'} <span>● В СЕТИ</span></div><div class="vehicle-title">${esc(vehicleName())}</div><div class="vehicle-sub">${esc(state.vehicle.year)} год · индивидуальный график обслуживания</div><div class="hero-footer"><div><div class="mileage-label">ТЕКУЩИЙ ПРОБЕГ</div><div class="mileage-number">${fmtKm(state.vehicle.mileage)} <span>км</span></div><div class="muted small">${state.vehicle.mileageUpdatedAt ? `обновлено ${fmtDate(state.vehicle.mileageUpdatedAt)}` : 'пробег ещё не обновлялся'}</div></div><button class="tiny-action" data-action="update-mileage">+ Внести пробег</button></div></div></section>
      ${age ? `<div class="warning-card"><div class="tip-icon">⚠</div><p><strong>${age === 'critical' ? 'Автомобиль очень возрастной.' : 'Машине уже больше 15 лет.'}</strong><br>Проверяйте резиновые детали, проводку и коррозию чаще обычного.</p></div>` : ''}
      ${mileageReminderDue() ? `<div class="warning-card"><div class="tip-icon">↻</div><p><strong>Пора обновить пробег.</strong><br>Прошло ${state.vehicle.reminderFrequency} дней с последней записи — это отдельное напоминание, не привязанное к ТО.</p></div>` : ''}
      <section><div class="section-head"><div><span class="section-kicker">Статус заезда</span><h2>Состояние машины</h2></div><span class="status-word ${overall.key}">${overall.label}</span></div><div class="status-card race-card"><div class="status-row"><div class="status-label"><i class="status-dot ${overall.key}"></i>ГОТОВА К ДОРОГЕ</div><span class="hud-code">СИСТ.${state.items.filter(i => getStatus(i).key === 'good').length}/${state.items.length}</span></div><div class="wear-bar"><div class="wear-fill ${overall.key}" style="width:${overall.key === 'good' ? 28 : overall.key === 'warn' ? 66 : overall.key === 'danger' ? 92 : 48}%"></div></div><div class="wear-scale"><span>НОРМА</span><span>ВНИМАНИЕ</span><span>СЕРВИС</span></div><p class="status-note">${overall.key === 'good' ? 'Никаких срочных действий. Так держать — данные обновлены.' : overall.key === 'danger' ? 'Есть задачи, которые уже вышли за рекомендованный срок.' : overall.key === 'warn' ? 'Пара пунктов приближается к нормативу — лучше запланировать заранее.' : 'Заполните историю замен, чтобы шкала стала точнее.'}</p></div></section>
      <section><div class="section-head"><div><span class="section-kicker">Внимание</span><h2>Ближайшие задачи</h2></div><button class="link-btn" data-page="schedule">Весь график →</button></div><div class="priority-list">${urgent.length ? urgent.map(serviceCard).join('') : `<div class="tip-card"><div class="tip-icon">✦</div><p>Все регламентные работы под контролем. Не забывайте обновлять пробег каждые ${weeksWord(state.vehicle.reminderFrequency / 7)}.</p></div>`}</div></section>
      <section><div class="section-head"><div><span class="section-kicker">Подсказка</span><h2>Не теряйте историю</h2></div></div><div class="tip-card"><div class="tip-icon">▣</div><p>Фотографии чеков и деталей хранятся внутри AutoPulse. Даже если удалить оригинал из галереи, копия останется в приложении.</p></div></section>
    </main>`;
  }
  function serviceCard(item) { const s = getStatus(item); return `<article class="service-card" data-item="${item.id}"><div class="service-icon">${icons[item.id] || icons.custom}</div><div class="service-copy"><div class="service-name">${esc(item.name)}</div><div class="service-detail">${s.note}</div></div><div class="service-side"><div class="service-status ${s.key}">${s.label}</div><div class="service-arrow">›</div></div></article>`; }
  function schedulePage() { const grouped = ['all', 'replace', 'check']; return `<main class="screen page-enter"><header class="topbar"><div><div class="eyebrow">Race planner / 02</div><h1>График ТО</h1></div><button class="icon-btn" data-action="edit-vehicle">⚙</button></header><div class="tip-card neon-tip"><div class="tip-icon">⌁</div><p>Сработает то, что наступит раньше: <strong>пробег или время.</strong> Для тормозной жидкости срок важнее километров.</p></div><div class="schedule-filter">${grouped.map((x,i) => `<button class="filter-btn ${i === 0 ? 'active' : ''}" data-filter="${x}">${x === 'all' ? 'Всё' : x === 'replace' ? 'Замены' : 'Проверки'}</button>`).join('')}</div><div class="schedule-grid">${state.items.map(scheduleCard).join('')}</div><div class="tip-card source-note"><div class="tip-icon">ⓘ</div><p><strong>Средний профиль.</strong> Значения рассчитаны как середина заданных диапазонов: иномарка — 11 500 км / 9 мес. для масла, отечественная — 10 000 км / 8 мес. Остальные позиции усреднены аналогично. Точный регламент конкретной модификации можно задать вручную.</p></div></main>`; }
  function scheduleCard(item) { const s = getStatus(item), c = currentItem(item); const interval = item.kind === 'check' ? 'По фактическому износу' : `${c.targetKm ? fmtKm(c.targetKm) + ' км' : '—'} ${c.targetMonths ? ' / ' + c.targetMonths + ' мес.' : ''}`; return `<article class="schedule-card" data-kind="${item.kind}" data-item="${item.id}"><div class="schedule-top"><div class="schedule-title"><div class="service-icon">${icons[item.id] || icons.custom}</div><div><h3>${esc(item.name)}</h3><div class="range-text">${esc(item.description || interval)}</div></div></div><span class="service-status ${s.key}">${s.label}</span></div><div class="wear-bar"><div class="wear-fill ${s.key}" style="width:${s.percent || (item.kind === 'check' ? 5 : 3)}%"></div></div><div class="wear-scale"><span>${item.kind === 'check' ? 'КОНТРОЛЬ СТАНДАРТА' : s.note}</span><span>${item.photos?.length ? `▣ ${item.photos.length}` : ''}</span></div><div class="schedule-actions"><button class="link-btn" data-item-action="edit" data-item-id="${item.id}">${item.lastDate ? 'Изменить запись →' : 'Добавить замену →'}</button></div></article>`; }
  function historyPage() { const all = state.items.flatMap(item => (item.records || []).map((r, index) => ({ ...r, item, recordIndex: index }))).sort((a,b) => new Date(b.date) - new Date(a.date)); return `<main class="screen"><header class="topbar"><div><div class="eyebrow">Журнал</div><h1>История работ</h1></div><button class="primary-btn" data-action="quick-record">+ Запись</button></header>${all.length ? `<div class="history-list">${all.map(r => `<article class="history-row"><div class="history-date">${new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short'}).format(new Date(r.date))}</div><div class="history-info"><strong>${esc(r.item.name)}</strong><p>${fmtKm(r.mileage)} км ${r.note ? `· ${esc(r.note)}` : ''}</p></div>${r.photos?.length ? `<span class="photo-count">▣ ${r.photos.length}</span>` : ''}<button class="history-delete" data-action="delete-record" data-item-id="${r.item.id}" data-record-index="${r.recordIndex}" aria-label="Удалить запись">×</button></article>`).join('')}</div>` : `<div class="history-empty"><div class="empty-icon">◷</div><h3>История пока пустая</h3><p>Добавьте первую замену или проверку — так AutoPulse научится считать износ точнее.</p><button class="primary-btn" data-action="quick-record">Добавить работу</button></div>`}</main>`; }
  function bottomNav() { return `<nav class="bottom-nav"><button class="nav-btn ${state.page === 'home' ? 'active' : ''}" data-page="home"><span class="nav-symbol">⌂</span>Главная</button><button class="nav-btn ${state.page === 'schedule' ? 'active' : ''}" data-page="schedule"><span class="nav-symbol">◴</span>График</button><button class="nav-btn ${state.page === 'history' ? 'active' : ''}" data-page="history"><span class="nav-symbol">▤</span>История</button></nav>`; }

  function renderOnboarding() { const d = onboardingDraft || {}; const steps = [1,2,3,4]; app.innerHTML = `<main class="onboarding"><div class="onboard-brand"><span class="brand-mark">A</span> AUTOPULSE</div><div class="progress">${steps.map(s => `<i class="${s <= onboardingStep ? 'on' : ''}"></i>`).join('')}</div><div class="onboard-body">${onboardingContent(d)}</div><div class="onboard-bottom">${onboardingStep > 1 ? `<div class="onboard-actions"><button class="ghost-btn" data-action="onboard-back">Назад</button><button class="primary-btn" data-action="onboard-next">${onboardingStep === 4 ? 'В гараж' : 'Продолжить'}</button></div>` : `<button class="primary-btn full" data-action="onboard-next">Начать настройку →</button>`}</div></main>`; bindAppEvents(); }
  function onboardingContent(d) { if (onboardingStep === 1) return `<div class="step-label">Шаг 01 / Профиль авто</div><h1>Знаем машину.<br><span style="color:var(--lime)">Берём ТО под контроль.</span></h1><p class="onboard-lead">Выберите профиль — AutoPulse подберёт базовые интервалы именно под него. Их можно будет изменить вручную.</p>`; if (onboardingStep === 2) return `<div class="step-label">Шаг 02 / Что за автомобиль?</div><h1>Расскажите<br>про своего зверя.</h1><div class="choice-grid onboard-select"><button class="choice ${d.type === 'foreign' ? 'selected' : ''}" data-choice="type" data-value="foreign"><div class="choice-icon">✦</div><strong>Иностранная</strong><span>Toyota, BMW, Kia и другие</span></button><button class="choice ${d.type === 'domestic' ? 'selected' : ''}" data-choice="type" data-value="domestic"><div class="choice-icon">⌁</div><strong>Отечественная</strong><span>Lada, ВАЗ, УАЗ и другие</span></button></div><div class="form-grid onboard-select"><div class="two-col"><div class="field"><label>Марка</label><input id="ob-make" value="${esc(d.make || '')}" placeholder="Lada"></div><div class="field"><label>Модель</label><input id="ob-model" value="${esc(d.model || '')}" placeholder="Vesta"></div></div><div class="field"><label>Год выпуска</label><input id="ob-year" type="number" min="1950" max="${new Date().getFullYear()}" value="${esc(d.year || '')}" placeholder="2020"></div></div>`; if (onboardingStep === 3) return `<div class="step-label">Шаг 03 / Точка отсчёта</div><h1>Где мы сейчас?</h1><p class="onboard-lead">Пробег будет нужен для точных напоминаний. Вносить его можно прямо с главного экрана.</p><div class="form-grid onboard-select"><div class="field"><label>Текущий пробег</label><input id="ob-mileage" inputmode="numeric" type="number" min="0" value="${esc(d.mileage || '')}" placeholder="Например, 86 400"></div><div class="field"><label>Как часто напоминать обновить пробег?</label><select id="ob-frequency"><option value="7" ${d.reminderFrequency == 7 ? 'selected' : ''}>Раз в неделю</option><option value="14" ${!d.reminderFrequency || d.reminderFrequency == 14 ? 'selected' : ''}>Раз в две недели</option><option value="30" ${d.reminderFrequency == 30 ? 'selected' : ''}>Раз в месяц</option></select></div></div>`; return `<div class="step-label">Шаг 04 / История</div><h1>Не помните,<br>что меняли?</h1><p class="onboard-lead">Это нормально. Отметьте неизвестные пункты — мы не будем придумывать даты, а покажем их как «нет данных», чтобы вы проверили всё при случае.</p><div class="onboard-select"><div class="mini-check"><input type="checkbox" id="ob-unknown" checked><label for="ob-unknown"><strong>Начать с чистого листа</strong><br>Все элементы будут ждать вашей первой записи.</label></div><div class="mini-check"><input type="checkbox" id="ob-reminder" checked><label for="ob-reminder"><strong>Включить мягкие напоминания</strong><br>Подсказывать об обновлении пробега и ближайшем ТО.</label></div></div>`; }

  function modalMarkup() { if (activeModal === 'mileage') return mileageModal(); if (activeModal === 'vehicle') return vehicleModal(); if (activeModal === 'picker') return recordPickerModal(); if (activeModal === 'item') return itemModal(); return ''; }
  function modalWrap(title, subtitle, body, centered = false) { return `<div class="modal-backdrop ${centered ? 'modal-centered' : ''}" data-action="close-modal"><section class="modal" data-modal-content><div class="modal-head"><div><h2>${title}</h2>${subtitle ? `<p>${subtitle}</p>` : ''}</div><button class="modal-close" data-action="close-modal">×</button></div>${body}</section></div>`; }
  function recordPickerModal() { return modalWrap('Что обслуживали?', 'Выберите готовый пункт или добавьте любую свою работу.', `<div class="record-picker">${state.items.map(item => `<button class="record-choice" data-record-item="${item.id}"><span class="record-choice-icon">${icons[item.id] || icons.custom}</span><span><strong>${esc(item.name)}</strong><small>${item.kind === 'check' ? 'Проверка состояния' : 'Замена / ремонт'}</small></span><b>›</b></button>`).join('')}<button class="record-choice custom-choice" data-action="new-custom-item"><span class="record-choice-icon">＋</span><span><strong>Новая работа</strong><small>Любая деталь или ремонт</small></span><b>›</b></button></div>`); }
  function mileageModal() { return modalWrap('Обновить пробег', 'Отдельно от ТО — просто зафиксируйте текущие цифры на одометре.', `<div class="form-grid"><div class="field"><label>Текущий пробег, км</label><input id="mileage-value" type="number" min="${state.vehicle.mileage}" value="${state.vehicle.mileage || ''}" autofocus></div><p class="muted small">Следующее напоминание об обновлении появится через ${state.vehicle.reminderFrequency} ${state.vehicle.reminderFrequency === 1 ? 'неделю' : 'недели'} после этой записи.</p></div><div class="modal-actions"><button class="primary-btn full" data-action="save-mileage">Сохранить пробег</button></div>`); }
  function vehicleModal() { return modalWrap('Профиль автомобиля', 'Измените данные машины и нормативный профиль.', `<div class="form-grid"><div class="choice-grid"><button class="choice ${state.vehicle.type === 'foreign' ? 'selected' : ''}" data-choice="vehicle-type" data-value="foreign"><strong>Иностранная</strong><span>Более длинные интервалы</span></button><button class="choice ${state.vehicle.type === 'domestic' ? 'selected' : ''}" data-choice="vehicle-type" data-value="domestic"><strong>Отечественная</strong><span>Чуть более короткие интервалы</span></button></div><div class="two-col"><div class="field"><label>Марка</label><input id="vehicle-make" value="${esc(state.vehicle.make)}"></div><div class="field"><label>Модель</label><input id="vehicle-model" value="${esc(state.vehicle.model)}"></div></div><div class="field"><label>Год выпуска</label><input id="vehicle-year" type="number" value="${state.vehicle.year}"></div><div class="field"><label>Пробег напоминать обновить</label><select id="vehicle-frequency"><option value="7" ${state.vehicle.reminderFrequency == 7 ? 'selected' : ''}>Раз в неделю</option><option value="14" ${state.vehicle.reminderFrequency == 14 ? 'selected' : ''}>Раз в две недели</option><option value="30" ${state.vehicle.reminderFrequency == 30 ? 'selected' : ''}>Раз в месяц</option></select></div><div class="mini-check"><input type="checkbox" id="vehicle-severe" ${state.vehicle.severeUse ? 'checked' : ''}><label for="vehicle-severe"><strong>Тяжёлые условия эксплуатации</strong><br>Короткие поездки, пробки, пыль, сильный мороз, такси, буксировка. Для пробеговых интервалов берём запас 25%.</label></div><div class="backup-box"><strong>Резервная копия</strong><span>Файл хранится у вас и не отправляется на сервер.</span><div class="backup-actions"><button class="ghost-btn" data-action="export-backup">Экспорт</button><button class="ghost-btn" data-action="pick-backup">Импорт</button><input id="backup-input" type="file" accept="application/json,.json" hidden></div></div></div><div class="modal-actions"><button class="primary-btn full" data-action="save-vehicle">Сохранить профиль</button></div>`); }
  function itemModal() { const isCustom = activeItemId === 'new'; const item = isCustom ? customDraft : state.items.find(i => i.id === activeItemId); const c = isCustom ? item : currentItem(item); return modalWrap(isCustom ? 'Новая работа' : 'Изменить работу', isCustom ? 'Назовите ремонт или деталь и задайте собственное напоминание.' : item.description, `<div class="form-grid"><div class="field"><label>Название работы или детали</label><input id="item-name" value="${esc(item.name)}" placeholder="Например: Замена рычага задней подвески"></div><div class="field"><label>${item.kind === 'check' ? 'Дата последней проверки' : 'Когда обслужили / заменили'}</label><input id="item-date" type="date" value="${item.lastDate ? new Date(item.lastDate).toISOString().slice(0,10) : ''}"></div><div class="field"><label>Пробег на тот момент</label><input id="item-mileage" type="number" min="0" value="${item.lastMileage ?? state.vehicle.mileage}"></div><div class="field"><label>Своя заметка</label><textarea id="item-note" placeholder="Например: заменили вместе с поддоном АКПП...">${esc(item.records?.[item.records.length - 1]?.note || '')}</textarea></div><div class="field"><label>Фото чека или детали</label><div class="photo-strip">${(item.photos || []).map((p,i) => `<div class="photo-thumb"><img src="${p}" alt="Фото ${i+1}"><button class="photo-remove" data-photo-index="${i}">×</button></div>`).join('')}<button class="photo-add" data-action="pick-photo">+</button><input id="photo-input" type="file" accept="image/*" multiple hidden></div><span class="muted small">Копии хранятся внутри приложения и не зависят от галереи.</span></div><div class="two-col"><div class="field"><label>Напомнить через, км</label><input id="item-km" type="number" min="0" value="${c.targetKm ?? ''}" ${item.kind === 'check' ? 'disabled' : ''}></div><div class="field"><label>Напомнить через, мес.</label><input id="item-months" type="number" min="0" value="${c.targetMonths ?? ''}" ${item.kind === 'check' ? 'disabled' : ''}></div></div>${isCustom ? '<p class="muted small">Можно указать один или оба интервала. Напоминание сработает по тому, что наступит раньше.</p>' : `<p class="muted small">Название и интервал можно изменить под свою машину.</p>`}</div><div class="modal-actions"><button class="ghost-btn" data-action="cancel-item">Отмена</button><button class="primary-btn" data-action="save-item">Сохранить</button></div>`); }

  function bindAppEvents() { app.querySelectorAll('[data-page]').forEach(el => el.addEventListener('click', () => { state.page = el.dataset.page; save(); render(); })); app.querySelectorAll('[data-item]').forEach(el => el.addEventListener('click', () => openItem(el.dataset.item))); app.querySelectorAll('[data-record-item]').forEach(el => el.addEventListener('click', () => openItem(el.dataset.recordItem))); app.querySelectorAll('[data-action]').forEach(el => el.addEventListener('click', handleAction)); app.querySelector('#photo-input')?.addEventListener('change', handlePhotos); app.querySelector('#backup-input')?.addEventListener('change', e => importBackup(e.target.files[0])); app.querySelectorAll('[data-item-action="edit"]').forEach(el => el.addEventListener('click', e => { e.stopPropagation(); openItem(el.dataset.itemId); })); app.querySelectorAll('[data-filter]').forEach(el => el.addEventListener('click', () => { app.querySelectorAll('.filter-btn').forEach(x => x.classList.remove('active')); el.classList.add('active'); const val = el.dataset.filter; app.querySelectorAll('.schedule-card').forEach(card => card.style.display = val === 'all' || card.dataset.kind === val ? '' : 'none'); })); app.querySelectorAll('[data-choice]').forEach(el => el.addEventListener('click', () => { const group = el.dataset.choice; if (group === 'type' && onboardingDraft) onboardingDraft.type = el.dataset.value; if (group === 'vehicle-type') state.vehicle.type = el.dataset.value; render(); })); app.querySelectorAll('[data-photo-index]').forEach(el => el.addEventListener('click', e => { e.stopPropagation(); const item = activeItemId === 'new' ? customDraft : state.items.find(i => i.id === activeItemId); item.photos.splice(Number(el.dataset.photoIndex), 1); save(); render(); })); }
  function handleAction(e) { const action = e.currentTarget.dataset.action; if (action === 'update-mileage') { activeModal = 'mileage'; render(); setTimeout(() => document.querySelector('#mileage-value')?.focus(), 30); } else if (action === 'edit-vehicle') { activeModal = 'vehicle'; render(); } else if (action === 'close-modal' && !e.target.closest('[data-modal-content]')) { activeModal = null; render(); } else if (action === 'close-modal' && e.currentTarget.classList.contains('modal-close')) { activeModal = null; render(); } else if (action === 'save-mileage') saveMileage(); else if (action === 'save-vehicle') saveVehicle(); else if (action === 'export-backup') exportBackup(); else if (action === 'pick-backup') document.querySelector('#backup-input')?.click(); else if (action === 'delete-record') deleteRecord(e.currentTarget.dataset.itemId, Number(e.currentTarget.dataset.recordIndex)); else if (action === 'cancel-item') { activeModal = null; customDraft = null; render(); } else if (action === 'save-item') saveItem(); else if (action === 'pick-photo') document.querySelector('#photo-input')?.click(); else if (action === 'quick-record') { activeModal = 'picker'; render(); } else if (action === 'new-custom-item') { customDraft = { id: `custom-${Date.now()}`, custom: true, name: '', description: 'Пользовательская работа', kind: 'replace', customKm: null, customMonths: null, lastMileage: null, lastDate: null, records: [], photos: [] }; activeItemId = 'new'; activeModal = 'item'; render(); } else if (action === 'onboard-next') nextOnboarding(); else if (action === 'onboard-back') { onboardingStep--; render(); } }
  function saveMileage() { const input = Number(document.querySelector('#mileage-value')?.value); if (!Number.isFinite(input) || input < state.vehicle.mileage) return showToast('Пробег не может быть меньше текущего'); state.vehicle.mileage = input; state.vehicle.mileageUpdatedAt = new Date().toISOString(); save(); activeModal = null; render(); showToast('Пробег обновлён'); }
  function saveVehicle() { state.vehicle.make = document.querySelector('#vehicle-make')?.value.trim() || ''; state.vehicle.model = document.querySelector('#vehicle-model')?.value.trim() || ''; state.vehicle.year = Number(document.querySelector('#vehicle-year')?.value) || state.vehicle.year; state.vehicle.reminderFrequency = Number(document.querySelector('#vehicle-frequency')?.value) || 14; state.vehicle.severeUse = Boolean(document.querySelector('#vehicle-severe')?.checked); save(); activeModal = null; render(); showToast('Профиль сохранён'); }
  function openItem(id) { activeItemId = id; activeModal = 'item'; render(); }
  function saveItem() { const isCustom = activeItemId === 'new'; const item = isCustom ? customDraft : state.items.find(i => i.id === activeItemId); const name = document.querySelector('#item-name')?.value.trim() || ''; const date = document.querySelector('#item-date')?.value; if (!name) return showToast('Введите название работы'); item.name = name; if (!date) return showToast('Укажите дату работы'); const mileage = Number(document.querySelector('#item-mileage')?.value); item.lastDate = new Date(`${date}T12:00:00`).toISOString(); item.lastMileage = Number.isFinite(mileage) ? mileage : state.vehicle.mileage; item.customKm = Number(document.querySelector('#item-km')?.value) || null; item.customMonths = Number(document.querySelector('#item-months')?.value) || null; item.description = isCustom ? 'Пользовательская работа' : item.description; const note = document.querySelector('#item-note')?.value.trim() || ''; item.records = [...(item.records || []), { date: item.lastDate, mileage: item.lastMileage, note, photos: [...(item.photos || [])] }]; if (isCustom) { state.items.push(item); customDraft = null; } save(); activeModal = null; render(); showToast('Запись добавлена в журнал'); }
  function deleteRecord(itemId, recordIndex) { const item = state.items.find(i => i.id === itemId); if (!item || !item.records?.[recordIndex]) return; if (!window.confirm('Удалить эту запись из истории?')) return; item.records.splice(recordIndex, 1); if (item.custom === true && item.records.length === 0) { state.items = state.items.filter(i => i.id !== itemId); } else { const last = item.records.slice().sort((a, b) => new Date(b.date) - new Date(a.date))[0]; item.lastDate = last?.date || null; item.lastMileage = last?.mileage ?? null; } save(); render(); showToast('Запись удалена'); }
  function handlePhotos(e) { const item = activeItemId === 'new' ? customDraft : state.items.find(i => i.id === activeItemId); [...e.target.files].forEach(file => { const reader = new FileReader(); reader.onload = ev => compressImage(ev.target.result).then(data => { item.photos = [...(item.photos || []), data]; save(); render(); }); reader.readAsDataURL(file); }); }
  function compressImage(src) { return new Promise(resolve => { const img = new Image(); img.onload = () => { const max = 1100, scale = Math.min(1, max / Math.max(img.width, img.height)), c = document.createElement('canvas'); c.width = Math.round(img.width * scale); c.height = Math.round(img.height * scale); c.getContext('2d').drawImage(img, 0, 0, c.width, c.height); resolve(c.toDataURL('image/jpeg', .78)); }; img.src = src; }); }
  function nextOnboarding() { if (onboardingStep === 1) { onboardingDraft = { type: 'foreign', make: '', model: '', year: new Date().getFullYear() - 5, mileage: '', reminderFrequency: 14 }; onboardingStep = 2; } else if (onboardingStep === 2) { onboardingDraft.make = document.querySelector('#ob-make')?.value.trim(); onboardingDraft.model = document.querySelector('#ob-model')?.value.trim(); onboardingDraft.year = Number(document.querySelector('#ob-year')?.value) || new Date().getFullYear() - 5; if (!onboardingDraft.make || !onboardingDraft.model) return showToast('Введите марку и модель'); onboardingStep = 3; } else if (onboardingStep === 3) { onboardingDraft.mileage = Number(document.querySelector('#ob-mileage')?.value); onboardingDraft.reminderFrequency = Number(document.querySelector('#ob-frequency')?.value); if (!Number.isFinite(onboardingDraft.mileage) || onboardingDraft.mileage < 0) return showToast('Укажите текущий пробег'); onboardingStep = 4; } else { state.onboarded = true; state.vehicle = { ...state.vehicle, ...onboardingDraft, mileageUpdatedAt: new Date().toISOString() }; onboardingDraft = null; save(); } render(); }
  function showToast(text) { const el = document.querySelector('#toast'); if (!el) return; el.textContent = text; el.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => el.classList.remove('show'), 2800); }

  app.innerHTML = '<div class="loading">AUTOPULSE // ЗАГРУЗКА ЛОКАЛЬНЫХ ДАННЫХ</div>';
  loadState().then(saved => { state = saved; render(); });
})();
